### ISSUE TITLE
Shortener 

### ISSUE THREAD

**Issue by Suyashjain05** [magneto261290/magneto-python-aria#21] opened 2020-08-30 20:02 UTC
Hey there, can you add url shortener support too?
Will assign api key for the shortener and the api url in config.env.

**Comment by magneto261290** [comment] 2020-08-31 02:03
I am ready to add but the problem is everyone wants different shortner. Some people want gplinks, some want shrinkme.. and many different shortners. How to deal with it??

**Comment by Suyashjain05** [comment] 2020-08-31 03:35
I knew this was gonna come up sooner or later.
Well the solution is simple, you can added the element too which is to be parsed in config.env, cause after all all shorteners works on similar kind of api and gives response in json, so you can let the user decide which shortener they want to use by letting then set up 'API_URL' 'API_KEY' & 'JSON_KEY'

**Comment by Suyashjain05** [comment] 2020-08-31 03:50
For ex.
For exe.io 
The response is like this
`
{"status":"success","shortenedUrl":""https:\/\/exe.io\/xxxxx`

Here the shortened url element is 'shortenedUrl' 

For GPlink too 
It's same 

So here you let the user decide according to his shortener what would be his json element which needs to be parsed. 
You get me?

**Comment by Suyashjain05** [comment] 2020-08-31 03:55
Just checked for shrinkme.io and it's same for shrinkme too.

`{"status":"success","shortenedUrl":""https:\/\/shrinkme.io\/xxxxx""}`

**Comment by magneto261290** [comment] 2020-08-31 05:10
I have checked gplinks, exe.io, shrinkme, shortex etc... everyone's response is same. and BTW we are not going to use json response. We will use text response.

**Comment by Suyashjain05** [comment] 2020-08-31 05:31
no no, i am talking about the response we'll get from the URL shortener's api

**Comment by magneto261290** [comment] 2020-09-02 11:41
I have added shortener support but some shorteners like adf.ly. shorte.st are not supported bcoz their api request url is different.
I am closing this issue. You can talk to me on Telegram. My username is [@The_magneto](https://t.me/The_magneto)

**Closed by magneto261290** 2020-09-02 11:41 UTC
